export const FETCHING_TYPES = 'FETCHING_TYPES';
export const FETCHING_TYPES_FULFILLED = 'FETCHING_TYPES_FULFILLED';
export const FETCHING_TYPES_REJECTED = 'FETCHING_TYPES_REJECTED';
export const TYPE_CHANGED = 'TYPE_CHANGED';

export const FETCHING_POKEMONS = 'FETCHING_POKEMONS';
export const FETCHING_POKEMONS_REJECTED = 'FETCHING_POKEMONS_REJECTED';
export const FETCHING_POKEMONS_FULFILLED = 'FETCHING_POKEMONS_FULFILLED';

export const PER_PAGE_CHANGED = 'PER_PAGE_CHANGED';
export const ACTIVE_PAGE_CHANGED = 'ACTIVE_PAGE_CHANGED';